// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type ObjectResponse struct {
	ID        int     `json:"id"`
	Name      string  `json:"name"`
	Path      string  `json:"path"`
	Type      string  `json:"type"`
	Size      *int    `json:"size"`
	MimeType  *string `json:"mimeType"`
	UpdatedAt int     `json:"updatedAt"`
	CreatedAt int     `json:"createdAt"`
}

type UserProfileResponse struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}
