// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type UserProfileResponse struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}
