// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"time"
)

type ObjectResponse struct {
	ID        uint      `json:"id"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Type      string    `json:"type"`
	Size      *uint64   `json:"size"`
	MimeType  *string   `json:"mimeType"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type UserProfileResponse struct {
	ID       uint   `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
}
