// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserID   string `json:"userId"`
	Nickname string `json:"nickname"`
}
